# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dJGYYOzmgGsMi1CL5fiwish0UyFmcqqJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score, roc_curve, auc
from scipy.stats import norm
from IPython.display import display

# Load Dataset
file_path = "classification.csv"
df = pd.read_csv(file_path)

# Data Preparation
cat_feats = ['age_bin', 'capital_gl_bin', 'education_bin',
             'hours_per_week_bin', 'msr_bin', 'occupation_bin', 'race_sex_bin']

# Split dataset into train and test
y_train = df[df['flag']=='train']['y']
x_train = df[df['flag']=='train'][cat_feats]
x_train = pd.get_dummies(x_train, columns=cat_feats, drop_first=True)

y_test = df[df['flag']=='test']['y']
x_test = df[df['flag']=='test'][cat_feats]
x_test = pd.get_dummies(x_test, columns=cat_feats, drop_first=True)

# Convert to numpy arrays
x_train, y_train = x_train.values, y_train.values
x_test, y_test = x_test.values, y_test.values

# Apply manual feature scaling
mean_train = np.mean(x_train, axis=0)
std_train = np.std(x_train, axis=0)

x_train_scaled = (x_train - mean_train) / std_train
x_test_scaled = (x_test - mean_train) / std_train


"""Logistic Regression from Scratch"""
class LogisticRegressionScratch:
    def __init__(self, learning_rate=0.01, iterations=3000):
        self.learning_rate = learning_rate
        self.iterations = iterations
        self.w = None
        self.b = None

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.w = np.zeros(n_features)
        self.b = 0

        for _ in range(self.iterations):
            linear_model = np.dot(X, self.w) + self.b
            y_predicted = self.sigmoid(linear_model)

            dw = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
            db = (1 / n_samples) * np.sum(y_predicted - y)

            self.w -= self.learning_rate * dw
            self.b -= self.learning_rate * db

    def predict_proba(self, X):
        return self.sigmoid(np.dot(X, self.w) + self.b)

    def predict(self, X, threshold=0.5):
        y_pred_proba = self.predict_proba(X)
        return (y_pred_proba >= threshold).astype(int)


"""Train and Evaluate Models"""
# Train Models with different learning rates and iterations
learning_rates = [0.01, 0.0001, 0.001]
iterations = [3000, 5000, 1000]

results = {}

for lr, iters in zip(learning_rates, iterations):
    print(f"Training Logistic Regression with learning rate {lr} and iterations {iters}")
    lr_model = LogisticRegressionScratch(learning_rate=lr, iterations=iters)
    lr_model.fit(x_train_scaled, y_train)

    y_pred_lr = lr_model.predict(x_test_scaled)
    y_prob_lr = lr_model.predict_proba(x_test_scaled)

    # Compute metrics
    cm_lr = confusion_matrix(y_test, y_pred_lr)
    TP = cm_lr[1, 1]
    TN = cm_lr[0, 0]
    FP = cm_lr[0, 1]
    FN = cm_lr[1, 0]

    precision_lr = precision_score(y_test, y_pred_lr)
    recall_lr = recall_score(y_test, y_pred_lr)
    accuracy_lr = accuracy_score(y_test, y_pred_lr)

    fpr_lr, tpr_lr, _ = roc_curve(y_test, y_prob_lr)
    auc_lr = auc(fpr_lr, tpr_lr)
    f_score_lr = 2 * (precision_lr * recall_lr) / (precision_lr + recall_lr)

    # Store results
    results[(lr, iters)] = {
        "TP": TP, "TN": TN, "FP": FP, "FN": FN,
        "Precision": precision_lr, "Recall": recall_lr, "Accuracy": accuracy_lr,
        "AUC": auc_lr, "F-score": f_score_lr
    }

    # Plot Confusion Matrix
    plt.figure(figsize=(6,5))
    sns.heatmap(cm_lr, annot=True, fmt='d', cmap='Blues', xticklabels=['Negative (0)', 'Positive (1)'], yticklabels=['Negative (0)', 'Positive (1)'])
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title(f"Confusion Matrix (LR, lr={lr}, iters={iters})")
    plt.show()

    # Plot ROC Curve
    plt.figure()
    # 加入隨機分類器的虛線 (y = x)
    plt.plot([0, 1], [0, 1], linestyle="--", color="gray", label="Random Classifier (AUC = 0.50)")
    plt.plot(fpr_lr, tpr_lr, label=f'Logistic Regression (AUC = {auc_lr:.2f})')
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title(f"ROC Curve (LR, lr={lr}, iters={iters})")
    plt.legend()
    plt.show()

# Convert results to DataFrame
df_results = pd.DataFrame(results).T

# Display results
print("Logistic Regression Results:")
display(df_results)

# Save results to CSV
df_results.to_csv("logistic_regression_results.csv", index=True)