# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8ZhmzwtYPevx-bLQEc7bgiBH5wbVz-4
"""

# ============================
# Step 1: Unzip Dataset
# ============================
import zipfile, os
zip_path     = 'dataset (1).zip'      # <- 改成你的檔名
extract_path = './dataset'
with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall(extract_path)
print("✅ Unzipped to:", os.path.abspath(extract_path))
print("Contents:", os.listdir(extract_path))

# ============================
# Step 2: Split Dataset into Train/Test
# ============================
import shutil, random

SOURCE_DIR = extract_path
TARGET_DIR = 'dataset_split'
train_ratio = 0.7
random.seed(42)

# 建目錄
for split in ['train','test']:
    for cls in os.listdir(SOURCE_DIR):
        os.makedirs(os.path.join(TARGET_DIR, split, cls), exist_ok=True)

# 分割並複製
for cls in os.listdir(SOURCE_DIR):
    cls_path = os.path.join(SOURCE_DIR, cls)
    if not os.path.isdir(cls_path):
        continue
    imgs = os.listdir(cls_path)
    random.shuffle(imgs)
    cut = int(len(imgs) * train_ratio)
    for img in imgs[:cut]:
        shutil.copyfile(os.path.join(cls_path, img),
                        os.path.join(TARGET_DIR, 'train', cls, img))
    for img in imgs[cut:]:
        shutil.copyfile(os.path.join(cls_path, img),
                        os.path.join(TARGET_DIR, 'test',  cls, img))

print("✅ Dataset split complete!")

# ============================
# Step 3: DataLoader & Preview
# ============================
import time, torch
from torch.utils.data import DataLoader
import torchvision, torchvision.transforms as T
import matplotlib.pyplot as plt

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

train_path = os.path.join(TARGET_DIR, 'train')
test_path  = os.path.join(TARGET_DIR, 'test')

transform = T.Compose([
    T.Resize((28,28)),
    T.Grayscale(num_output_channels=1),
    T.ToTensor(),
    T.Normalize((0.5,), (0.5,))
])

train_set = torchvision.datasets.ImageFolder(train_path, transform=transform)
test_set  = torchvision.datasets.ImageFolder(test_path,  transform=transform)

train_loader = DataLoader(train_set, batch_size=64, shuffle=True)
test_loader  = DataLoader(test_set,  batch_size=64, shuffle=False)

print("Classes:", train_set.classes)
print("Train samples:", len(train_set), "Test samples:", len(test_set))

def show_examples(ds, n_per_cls=2, title=""):
    cls_cnt = {i:0 for i in range(len(ds.classes))}
    imgs_col = {i:[] for i in range(len(ds.classes))}
    for img, lbl in ds:
        if cls_cnt[lbl] < n_per_cls:
            imgs_col[lbl].append(img)
            cls_cnt[lbl] += 1
        if all(v>=n_per_cls for v in cls_cnt.values()):
            break

    n_cls = len(ds.classes)
    fig, axes = plt.subplots(n_per_cls, n_cls, figsize=(n_cls*2, n_per_cls*2))
    for c in range(n_cls):
        for r in range(n_per_cls):
            ax = axes[r][c]
            im = imgs_col[c][r].numpy().transpose(1,2,0)*0.5 + 0.5
            ax.imshow(im.squeeze(), cmap='gray')
            ax.set_title(ds.classes[c], fontsize=8)
            ax.axis('off')
    plt.suptitle(title)
    plt.tight_layout()
    plt.show()

show_examples(train_set, 2, "Train Examples")
show_examples(test_set,  2, "Test Examples")

# ============================
# Step 4: Define ViT
# ============================
import torch.nn as nn
from einops import rearrange, repeat

def pair(t): return t if isinstance(t, tuple) else (t,t)

class PreNorm(nn.Module):
    def __init__(self, dim, fn):
        super().__init__()
        self.norm = nn.LayerNorm(dim)
        self.fn   = fn
    def forward(self, x, **kw):
        return self.fn(self.norm(x), **kw)

class FeedForward(nn.Module):
    def __init__(self, dim, hidden, dropout=0.):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(dim, hidden),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden, dim),
            nn.Dropout(dropout)
        )
    def forward(self, x): return self.net(x)

class Attention(nn.Module):
    def __init__(self, dim, heads=4, dim_head=64, dropout=0.):
        super().__init__()
        inner = dim_head * heads
        self.heads = heads
        self.scale = dim_head ** -0.5
        self.to_qkv = nn.Linear(dim, inner*3, bias=False)
        self.to_out = nn.Sequential(
            nn.Linear(inner, dim),
            nn.Dropout(dropout)
        )
    def forward(self, x):
        b,n,_ = x.shape
        qkv = self.to_qkv(x).chunk(3, dim=-1)
        q,k,v = map(lambda t: rearrange(t, 'b n (h d)-> b h n d', h=self.heads), qkv)
        attn = (q @ k.transpose(-2,-1)) * self.scale
        attn = attn.softmax(dim=-1)
        out  = attn @ v
        out  = rearrange(out, 'b h n d-> b n (h d)')
        return self.to_out(out)

class Transformer(nn.Module):
    def __init__(self, dim, depth, heads, dim_head, mlp_dim, dropout=0.):
        super().__init__()
        self.layers = nn.ModuleList()
        for _ in range(depth):
            self.layers.append(nn.ModuleList([
                PreNorm(dim, Attention(dim, heads, dim_head, dropout)),
                PreNorm(dim, FeedForward(dim, mlp_dim, dropout))
            ]))
    def forward(self, x):
        for attn, ff in self.layers:
            x = x + attn(x)
            x = x + ff(x)
        return x

class ViT(nn.Module):
    def __init__(self, image_size, patch_size, num_classes,
                 dim, depth, heads, mlp_dim,
                 channels=1, dim_head=64, dropout=0., emb_dropout=0.,
                 pool='cls'):
        super().__init__()
        h,w = pair(image_size); ph,pw = pair(patch_size)
        assert h%ph==0 and w%pw==0, "Patch must divide image"
        num_patches = (h//ph)*(w//pw)

        self.to_patch = nn.Conv2d(channels, dim, kernel_size=patch_size, stride=patch_size)
        self.cls_token     = nn.Parameter(torch.randn(1,1,dim))
        self.pos_embedding = nn.Parameter(torch.randn(1, num_patches+1, dim))
        self.dropout       = nn.Dropout(emb_dropout)

        self.transformer = Transformer(dim, depth, heads, dim_head, mlp_dim, dropout)
        self.pool        = pool
        self.mlp_head    = nn.Sequential(
            nn.LayerNorm(dim),
            nn.Linear(dim, num_classes)
        )

    def forward(self, img):
        x = self.to_patch(img)
        x = rearrange(x, 'b c h w-> b (h w) c')
        b,n,_ = x.shape
        cls = repeat(self.cls_token, '1 1 d-> b 1 d', b=b)
        x = torch.cat([cls, x], dim=1)
        x = x + self.pos_embedding[:,:n+1]
        x = self.dropout(x)
        x = self.transformer(x)
        x = x[:,0] if self.pool=='cls' else x.mean(dim=1)
        return self.mlp_head(x)

# ============================
# Step 5: Build & Summarize
# ============================
import torch
import torch.nn as nn
import torch.optim as optim

model = ViT(
    image_size=28,
    patch_size=4,
    num_classes=len(train_set.classes),
    channels=1,
    dim=128,
    depth=8,
    heads=6,
    mlp_dim=256,
    dropout=0.1,
    emb_dropout=0.1
).to(device)

# 替代 print(model)，產生圖二格式
from torch import nn
from torchinfo import summary
print(summary(model, input_size=(1, 1, 28, 28), depth=4))


# ============================
# Step 6: Training & Evaluation
# ============================
def train_epoch(model, loader, optimizer, criterion, device, log_interval=10000):
    model.train()
    running_loss = 0.0
    total_seen = 0

    for batch_idx, (data, target) in enumerate(loader):
        data, target = data.to(device), target.to(device)
        out = model(data)
        loss = criterion(out, target)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # 統計
        batch_size = data.size(0)
        running_loss += loss.item() * batch_size
        total_seen += batch_size

        # 每 log_interval 張圖顯示一次
        if total_seen % log_interval == 0 or total_seen == len(loader.dataset):
            avg_loss = running_loss / total_seen
            print(f"[{total_seen}/{len(loader.dataset)} ({100. * total_seen / len(loader.dataset):.0f}%)] "
                  f"Loss: {avg_loss:.4f}")
def evaluate(model, loader, criterion, device):
    model.eval()
    total_loss = 0.0
    correct    = 0

    with torch.no_grad():
        for data, target in loader:
            data, target = data.to(device), target.to(device)
            out = model(data)
            total_loss += criterion(out, target).item() * data.size(0)
            preds = out.argmax(dim=1)
            correct += (preds == target).sum().item()

    avg_loss = total_loss / len(loader.dataset)
    accuracy = correct / len(loader.dataset)

    # 印出平均測試損失與準確率
    print(f"\nAverage test loss: {avg_loss:.4f}  Accuracy: {correct}/{len(loader.dataset)} ({accuracy*100:.2f}%)\n")
    return avg_loss, accuracy

optimizer = optim.Adam(model.parameters(), lr=1e-3 ,weight_decay=1e-4 )
criterion = nn.CrossEntropyLoss()
n_epochs=5
for e in range(1,n_epochs+1):
    print(f"\nEpoch: {e}")
    train_epoch(model, train_loader, optimizer, criterion, device)
    evaluate(model, test_loader, criterion, device)

# ============================
# Step 7: Visualization (c & d)
# ============================
import numpy as np
import seaborn as sns
from sklearn.metrics import confusion_matrix
def plot_confusion_matrix(m, loader, classes, device):
    m.eval()
    all_p, all_t = [], []
    with torch.no_grad():
        for x,y in loader:
            x = x.to(device)
            out = m(x)
            preds = out.argmax(dim=1).cpu().numpy()
            all_p.extend(preds)
            all_t.extend(y.numpy())
    cm = confusion_matrix(all_t, all_p)
    plt.figure(figsize=(8,6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=classes, yticklabels=classes)
    plt.xlabel('Predicted'); plt.ylabel('Actual')
    plt.title('Confusion Matrix'); plt.tight_layout()
    plt.show()

def plot_classwise_predictions(m, loader, classes, per_cls=4, device=None):
    m.eval()
    collected = {i:[] for i in range(len(classes))}
    with torch.no_grad():
        for x,y in loader:
            x = x.to(device)
            out = m(x)
            preds = out.argmax(dim=1).cpu()
            for img, t, p in zip(x.cpu(), y, preds):
                ti = t.item()
                if len(collected[ti])<per_cls:
                    collected[ti].append((img,ti,p.item()))
            if all(len(v)==per_cls for v in collected.values()):
                break
    n_cls = len(classes)
    fig, axes = plt.subplots(n_cls, per_cls, figsize=(per_cls*2, n_cls*2))
    for c in range(n_cls):
        for i,(img,t,p) in enumerate(collected[c]):
            ax=axes[c][i]
            im=img.numpy().transpose(1,2,0)*0.5+0.5
            ax.imshow(im.squeeze(),cmap='gray')
            color='green' if t==p else 'red'
            ax.set_title(f"T:{classes[t]}\nP:{classes[p]}", color=color, fontsize=8)
            ax.axis('off')
    plt.tight_layout(); plt.show()

plot_confusion_matrix(model, test_loader, train_set.classes, device)
plot_classwise_predictions(model, test_loader, train_set.classes, per_cls=4, device=device)

!pip install torchinfo