# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jDju8b3iru0j_7ynsdXz_zHBhIB-EGcZ
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, Subset
import matplotlib.pyplot as plt
import os

# ====== 基本參數與資料載入 ======
LATENT_DIM = 100
BATCH = 64
EPOCHS = 50
LR = 0.0002
IMG_SHAPE = (1, 28, 28)
IMG_DIM = 1 * 28 * 28
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 預處理流程：標準化至 [-1, 1]
transform_ops = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

# 指定三類別：0, 1, 2 對應衣服褲子毛衣
LABEL_DICT = {0: "Tshirt", 1: "Trouser", 2: "Pullover"}
dataset = datasets.FashionMNIST(root="./data", train=True, download=True, transform=transform_ops)
subset_idx = {cls: [i for i, (_, y) in enumerate(dataset) if y == cls][:5000] for cls in LABEL_DICT}
subset_data = {cls: Subset(dataset, ids) for cls, ids in subset_idx.items()}
dataloaders = {cls: DataLoader(ds, batch_size=BATCH, shuffle=True) for cls, ds in subset_data.items()}

os.makedirs("./samples", exist_ok=True)

# ====== 生成器 (Generator) 定義 ======
class GenModel(nn.Module):
    def __init__(self, latent_dim, output_dim):
        super().__init__()
        self.fc1 = nn.Linear(latent_dim, 256)
        self.fc2 = nn.Linear(256, 512)
        self.fc3 = nn.Linear(512, 1024)
        self.fc4 = nn.Linear(1024, output_dim)
        self.activation = nn.Tanh()
        self.act_fn = nn.LeakyReLU(0.2)

    def forward(self, x):
        x = self.act_fn(self.fc1(x))
        x = self.act_fn(self.fc2(x))
        x = self.act_fn(self.fc3(x))
        x = self.activation(self.fc4(x))
        return x

# ====== 判別器 (Discriminator) 定義 ======
class DiscModel(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.layers = nn.ModuleList([
            nn.Linear(input_dim, 1024),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3),
            nn.Linear(1024, 512),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3),
            nn.Linear(512, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 1),
            nn.Sigmoid()
        ])

    def forward(self, x):
        for layer in self.layers:
            x = layer(x)
        return x

# ====== CycleGAN 的自編碼器結構 ======
class AutoCycleGen(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.fc1 = nn.Linear(dim, 512)
        self.fc2 = nn.Linear(512, 1024)
        self.fc3 = nn.Linear(1024, dim)
        self.act_relu = nn.ReLU()
        self.act_tanh = nn.Tanh()

    def forward(self, x):
        x = self.act_relu(self.fc1(x))
        x = self.act_relu(self.fc2(x))
        x = self.act_tanh(self.fc3(x))
        return x

# ====== GAN 訓練主程式 ======
def run_gan(generator, discriminator, loader, label_str):
    generator.train()
    discriminator.train()
    loss_fn = nn.BCELoss()
    opt_g = optim.Adam(generator.parameters(), lr=LR)
    opt_d = optim.Adam(discriminator.parameters(), lr=LR)

    for ep in range(EPOCHS):
        for real, _ in loader:
            real = real.view(-1, IMG_DIM).to(DEVICE)
            batch = real.size(0)

            # 生成標籤
            valid = torch.ones(batch, 1).to(DEVICE)
            fake = torch.zeros(batch, 1).to(DEVICE)

            # 訓練 D
            z = torch.randn(batch, LATENT_DIM).to(DEVICE)
            gen_imgs = generator(z)
            d_real = loss_fn(discriminator(real), valid)
            d_fake = loss_fn(discriminator(gen_imgs.detach()), fake)
            d_loss = d_real + d_fake

            opt_d.zero_grad()
            d_loss.backward()
            opt_d.step()

            # 訓練 G
            g_loss = loss_fn(discriminator(gen_imgs), valid)
            opt_g.zero_grad()
            g_loss.backward()
            opt_g.step()

        print(f"[{label_str}] Epoch {ep+1:03d}/{EPOCHS} | D Loss: {d_loss:.4f} | G Loss: {g_loss:.4f}")

    generator.eval()
    with torch.no_grad():
        z = torch.randn(BATCH, LATENT_DIM).to(DEVICE)
        output_imgs = generator(z).view(-1, *IMG_SHAPE)
    return output_imgs

# ====== CycleGAN 訓練主程式 ======
def run_cyclegan(model, loader):
    model.train()
    loss_fn = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=LR)

    for ep in range(EPOCHS):
        for real, _ in loader:
            real = real.view(-1, IMG_DIM).to(DEVICE)
            output = model(real)
            loss = loss_fn(output, real)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        print(f"[Cycle] Epoch {ep+1:03d}/{EPOCHS} | Loss: {loss:.4f}")

    model.eval()
    with torch.no_grad():
        result = model(real).view(-1, *IMG_SHAPE)
    return result

# ====== 圖像比對可視化 ======
def plot_result(real_imgs, gan_imgs, cyc_imgs, label_str, save_to):
    fig, axs = plt.subplots(3, 8, figsize=(14, 5))
    titles = ["Real", "GAN", "CycleGAN"]
    data_groups = [real_imgs, gan_imgs, cyc_imgs]

    for row in range(3):
        for col in range(8):
            axs[row, col].imshow(data_groups[row][col].squeeze().cpu(), cmap="gray")
            axs[row, col].axis("off")
            if col == 0:
                axs[row, col].set_title(titles[row])
    fig.suptitle(f"{label_str} - GAN vs CycleGAN", fontsize=14)
    plt.tight_layout()
    plt.savefig(save_to)
    plt.close()

# ====== 執行主流程 ======
for cls, label in LABEL_DICT.items():
    gen = GenModel(LATENT_DIM, IMG_DIM).to(DEVICE)
    disc = DiscModel(IMG_DIM).to(DEVICE)
    cycgen = AutoCycleGen(IMG_DIM).to(DEVICE)

    imgs_gan = run_gan(gen, disc, dataloaders[cls], label)
    imgs_cyc = run_cyclegan(cycgen, dataloaders[cls])
    real_batch, _ = next(iter(dataloaders[cls]))

    save_img = os.path.join("./samples", f"{label}_compare.png")
    plot_result(real_batch[:8], imgs_gan[:8], imgs_cyc[:8], label, save_img)