# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eBvVREfLEfXTNk69FMjYc5PQ7vAvV4yX
"""

# ========== 1. 套件與初始設定 ==========
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
import numpy as np
import os, random
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report

# ========== 2. 資料下載與解壓 ==========
import gdown, zipfile
file_id = "1eyrNGFlM83pf-TETo30Cvjm7kYuCFAqu"
gdown.download(f"https://drive.google.com/uc?id={file_id}", output="dataset.zip", quiet=False)
with zipfile.ZipFile("dataset.zip", 'r') as zip_ref:
    zip_ref.extractall("dataset")

# ========== 3. 資料整理 ==========
IMAGE_HEIGHT = 128
IMAGE_WIDTH = 128
BATCH_SIZE = 64

def get_pathframe(path):
    filenames = os.listdir(path)
    categories = []
    paths = []
    for filename in filenames:
        paths.append(path + filename)
        category = filename.split('.')[0]
        categories.append(1 if category == 'dog' else 0)
    return pd.DataFrame({'filename': filenames, 'category': categories, 'paths': paths})

df = get_pathframe("dataset/dataset/dataset/")

# ========== 4. 影像轉 Tensor ==========
def load_and_preprocess_image(path, augment=False):
    image = tf.io.read_file(path)
    image = tf.image.decode_jpeg(image, channels=3)
    image = tf.image.resize(image, [IMAGE_WIDTH, IMAGE_HEIGHT])
    image = image / 255.0
    if augment:
        image = tf.image.random_flip_left_right(image)
        image = tf.image.random_brightness(image, max_delta=0.1)
        image = tf.image.random_contrast(image, lower=0.9, upper=1.1)
    return image

def convert_to_tensor(df, augment=False):
    path_ds = tf.data.Dataset.from_tensor_slices(df['paths'])
    image_ds = path_ds.map(lambda x: load_and_preprocess_image(x, augment), num_parallel_calls=tf.data.AUTOTUNE)
    label_ds = tf.data.Dataset.from_tensor_slices(tf.cast(df['category'], tf.int64))
    return image_ds, label_ds

# 訓練集用資料增強，測試集不做增強
X_train, Y_train = convert_to_tensor(df.iloc[:22500], augment=True)
X_test, Y_test = convert_to_tensor(df.iloc[22500:], augment=False)

dataset_train = tf.data.Dataset.zip((X_train, Y_train)).shuffle(2000).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
dataset_test = tf.data.Dataset.zip((X_test, Y_test)).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

# ========== 5. CNN 模型設計與改良 ==========
def Improved_CNNmodel():
    model = models.Sequential()
    model.add(layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(128, 128, 3)))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D(2, 2))
    model.add(layers.Dropout(0.32))  # 原本 0.25 → 0.3

    model.add(layers.Conv2D(64, (3, 3), activation='relu', padding='same'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D(2, 2))
    model.add(layers.Dropout(0.3))

    model.add(layers.Conv2D(128, (3, 3), activation='relu', padding='same'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D(2, 2))
    model.add(layers.Dropout(0.3))

    model.add(layers.Flatten())
    model.add(layers.Dense(256, activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.Dropout(0.6))  # 原本 0.5 → 0.6

    model.add(layers.Dense(1, activation='sigmoid'))

    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model

model = Improved_CNNmodel()
model.summary()

# ========== 6. 模型訓練 ==========
early_stop = callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

hist = model.fit(dataset_train,
                 epochs=4,
                 validation_data=dataset_test,
                 callbacks=[early_stop])

# ========== 7. 模型儲存 ==========
model.save("313611104.keras")

# ========== 8. 繪圖：準確率與損失曲線 ==========
def plot_model_history(model_history):
    fig, axs = plt.subplots(1, 2, figsize=(15, 5))
    axs[0].plot(model_history.history['accuracy'])
    axs[0].plot(model_history.history['val_accuracy'])
    axs[0].set_title('Model Accuracy')
    axs[0].set_xlabel('Epoch')
    axs[0].set_ylabel('Accuracy')
    axs[0].legend(['Train', 'Validation'], loc='best')

    axs[1].plot(model_history.history['loss'])
    axs[1].plot(model_history.history['val_loss'])
    axs[1].set_title('Model Loss')
    axs[1].set_xlabel('Epoch')
    axs[1].set_ylabel('Loss')
    axs[1].legend(['Train', 'Validation'], loc='best')
    plt.tight_layout()
    plt.show()

plot_model_history(hist)

# ========== 9. 模型評估 ==========
loss, accuracy = model.evaluate(dataset_test)
print("Test: accuracy = %f ; loss = %f" % (accuracy, loss))

# ========== 10. 混淆矩陣與分類報告 ==========
y_pred = model.predict(dataset_test)
y_p = np.where(y_pred > 0.5, 1, 0)

y_g = []
for _, label in dataset_test.unbatch():
    y_g.append(label.numpy())
y_g = np.array(y_g).flatten()
y_p = y_p.flatten()

confusion_mtx = confusion_matrix(y_g, y_p)
plt.figure(figsize=(8, 8))
sns.heatmap(confusion_mtx, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")
plt.show()

report = classification_report(y_g, y_p, target_names=['Cat', 'Dog'])
print(report)