# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2O7NB4ZSs75AAaIOMGUVW3qQn1LHHVI
"""

# Load Dataset & 相關函數
import struct
import numpy as np
import matplotlib.pyplot as plt
import os
print(os.listdir())  # 列出目前目錄的所有檔案
# ========== Load IDX Files ==========
def load_images(filename):
    with open(filename, 'rb') as f:
        # 讀取魔術數、影像數、列數、欄數
        _, num, rows, cols = struct.unpack(">IIII", f.read(16))
        images = np.frombuffer(f.read(), dtype=np.uint8)
        # 保證讀取到完整的影像
        images = images[: (len(images) // (rows * cols)) * rows * cols]
        return images.reshape(-1, rows * cols).astype(np.float32) / 255.0

def load_labels(filename):
    with open(filename, 'rb') as f:
        _, num = struct.unpack(">II", f.read(8))
        labels = np.frombuffer(f.read(), dtype=np.uint8)
        return labels[:num]

# ========== 1. Sigmoid Function ==========
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# ========== 2. Mini Batch SGD: Algorithm 7.2 ==========
def sgd_minibatch(X, y, eta=0.01, max_iters=20000, batch_size=128):
    n, d = X.shape
    w = np.zeros(d)
    iter_count = 0
    indices = np.arange(n)
    np.random.shuffle(indices)
    batch_index = 0
    while iter_count < max_iters:
        if batch_index + batch_size > n:
            np.random.shuffle(indices)
            batch_index = 0
        batch_indices = indices[batch_index:batch_index+batch_size]
        X_batch = X[batch_indices]
        y_batch = y[batch_indices]
        preds = sigmoid(np.dot(X_batch, w))
        # 梯度： (1/batch_size) * X_batch^T * (preds - y_batch)
        grad = np.dot(X_batch.T, (preds - y_batch)) / batch_size
        w -= eta * grad
        batch_index += batch_size
        iter_count += 1
    return w

# ========== 3. Mini Batch SGD with Momentum: Algorithm 7.3 ==========
def sgd_minibatch_momentum(X, y, eta=0.02, max_iters=15000, batch_size=128, momentum=0.95):
    n, d = X.shape
    w = np.zeros(d)
    velocity = np.zeros(d)
    iter_count = 0
    indices = np.arange(n)
    np.random.shuffle(indices)
    batch_index = 0
    while iter_count < max_iters:
        if batch_index + batch_size > n:
            np.random.shuffle(indices)
            batch_index = 0
        batch_indices = indices[batch_index:batch_index+batch_size]
        X_batch = X[batch_indices]
        y_batch = y[batch_indices]
        preds = sigmoid(np.dot(X_batch, w))
        grad = np.dot(X_batch.T, (preds - y_batch)) / batch_size
        velocity = momentum * velocity - eta * grad
        w += velocity
        batch_index += batch_size
        iter_count += 1
    return w

# ========== 4. Mini Batch SGD with Nesterov Momentum (公式 7.34) ==========
def sgd_minibatch_nesterov(X, y, eta=0.05, max_iters=15000, batch_size=128, momentum=0.95):
    n, d = X.shape
    w = np.zeros(d)
    velocity = np.zeros(d)
    iter_count = 0
    indices = np.arange(n)
    np.random.shuffle(indices)
    batch_index = 0
    while iter_count < max_iters:
        if batch_index + batch_size > n:
            np.random.shuffle(indices)
            batch_index = 0
        batch_indices = indices[batch_index:batch_index+batch_size]
        X_batch = X[batch_indices]
        y_batch = y[batch_indices]
        # 預先「看前」：使用 momentum 調整後的位置
        w_lookahead = w + momentum * velocity
        preds = sigmoid(np.dot(X_batch, w_lookahead))
        grad = np.dot(X_batch.T, (preds - y_batch)) / batch_size
        velocity = momentum * velocity - eta * grad
        w += velocity
        batch_index += batch_size
        iter_count += 1
    return w

# ========== 5. Adam Optimizer: Algorithm 7.4 ==========
def sgd_Adam(X, y, eta=0.001, max_iters=15000, batch_size=128, beta1=0.85, beta2=0.999, delta=1e-8):
    print("X shape:", X.shape)
    n, d = X.shape
    w = np.zeros(d)
    s = np.zeros(d)  # 一階矩估計
    r = np.zeros(d)  # 二階矩估計
    iter_count = 0
    indices = np.arange(n)
    np.random.shuffle(indices)
    batch_index = 0
    while iter_count < max_iters:
        if batch_index + batch_size > n:
            np.random.shuffle(indices)
            batch_index = 0
        batch_indices = indices[batch_index:batch_index+batch_size]
        X_batch = X[batch_indices]
        y_batch = y[batch_indices]
        preds = sigmoid(np.dot(X_batch, w))
        grad = np.dot(X_batch.T, (preds - y_batch)) / batch_size
        s = beta1 * s + (1 - beta1) * grad
        r = beta2 * r + (1 - beta2) * (grad ** 2)
        s_hat = s / (1 - beta1**(iter_count+1))
        r_hat = r / (1 - beta2**(iter_count+1))
        w -= eta * s_hat / (np.sqrt(r_hat) + delta)
        batch_index += batch_size
        iter_count += 1
    return w

# ========== Show Misclassified Samples ==========
def show_misclassified(X, true_labels, pred_labels, max_show=10):
    mis_idx = np.where(true_labels != pred_labels)[0][:max_show]
    plt.figure(figsize=(10, 2))
    for i, idx in enumerate(mis_idx):
        plt.subplot(1, len(mis_idx), i + 1)
        # 注意：第一欄為 bias，所以從 index 1 開始 reshape 為 28x28
        plt.imshow(X[idx, 1:].reshape(28, 28), cmap='gray')
        plt.axis('off')
        plt.title(f"T:{true_labels[idx]}\nP:{pred_labels[idx]}")
    plt.suptitle("Misclassified Samples")
    plt.show()
#載入顯示圖樣數據模組
def info_log(msg):
    print(f"[INFO] {msg}")

def load_images_verbose(filename):
    with open(filename, 'rb') as f:
        magic, num, rows, cols = struct.unpack(">IIII", f.read(16))
        info_log(f"Header: {num} images, {rows}x{cols}")
        data = np.frombuffer(f.read(), dtype=np.uint8)
        info_log(f"Loading {num} images based on file size")
        return data.reshape(num, rows * cols).astype(np.float32) / 255.0

def load_labels_verbose(filename):
    with open(filename, 'rb') as f:
        magic, num = struct.unpack(">II", f.read(8))
        info_log(f"Loading {num} labels based on file size")
        return np.frombuffer(f.read(), dtype=np.uint8)

def evaluate_binary_classification(model_name, target_digit, preds, true_labels):
    info_log(f"Binary classification: '{target_digit}' vs not-{target_digit}")
    acc = np.mean(preds == true_labels)
    print(f"\nTest Accuracy (is {target_digit} or not): {acc:.4f}")

# ========== Main ==========
if __name__ == "__main__":
    # === Load Data ===
    X_train = load_images_verbose("train-images (1).idx3-ubyte____")
    y_train = load_labels_verbose("train-labels (1).idx1-ubyte____")
    X_test = load_images_verbose("t10k-images (1).idx3-ubyte____")
    y_test = load_labels_verbose("t10k-labels (1).idx1-ubyte____")

    # === Choose binary classification target digit ===
    TARGET_DIGIT = 4  # 可調整：0~9
    y_train_bin = np.where(y_train == TARGET_DIGIT, 1, 0)
    y_test_bin = np.where(y_test == TARGET_DIGIT, 1, 0)
    info_log(f"Binary classification: '{TARGET_DIGIT}' vs not-{TARGET_DIGIT}")

    # === Add bias term ===
    X_train = np.hstack([np.ones((X_train.shape[0], 1)), X_train])
    X_test = np.hstack([np.ones((X_test.shape[0], 1)), X_test])

    # === Choose optimizer ===
    optimizer = "adam"  # 選項： "sgd", "momentum", "nesterov", "adam"

    if optimizer == "sgd":
        info_log("Training with mini-batch SGD...")
        w = sgd_minibatch(X_train, y_train_bin, eta=0.01, max_iters=10000, batch_size=64)
    elif optimizer == "momentum":
        info_log("Training with SGD with Momentum...")
        w = sgd_minibatch_momentum(X_train, y_train_bin, eta=0.01, max_iters=10000, batch_size=64, momentum=0.9)
    elif optimizer == "nesterov":
        info_log("Training with SGD with Nesterov Momentum...")
        w = sgd_minibatch_nesterov(X_train, y_train_bin, eta=0.01, max_iters=10000, batch_size=64, momentum=0.9)
    elif optimizer == "adam":
        info_log("Training with Adam Optimizer...")
        w = sgd_Adam(X_train, y_train_bin, eta=0.001, max_iters=10000, batch_size=64, beta1=0.9, beta2=0.999, delta=1e-8)

    # === Predict on Test Set ===
    preds_test = sigmoid(np.dot(X_test, w)) >= 0.5
    preds_test = preds_test.astype(int)

    # === Evaluate Accuracy + Info Output ===
    evaluate_binary_classification(optimizer, TARGET_DIGIT, preds_test, y_test_bin)

    # === Show Misclassified Samples ===
    show_misclassified(X_test, y_test_bin, preds_test)