# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12umrOMymTbvZlV3RQ5nWqwoJNap-iUcD
"""

import numpy as np
import struct
import matplotlib.pyplot as plt

# ========== Load Dataset ==========
def load_images(filename):
    with open(filename, 'rb') as f:
        # 讀取檔案中的 magic number, 數量, 圖片列數與欄數
        _, num, rows, cols = struct.unpack(">IIII", f.read(16))
        data = np.frombuffer(f.read(), dtype=np.uint8).reshape((num, rows * cols))
    return data.astype(np.float32) / 255.0

def load_labels(filename):
    with open(filename, 'rb') as f:
        # 讀取檔案中的 magic number 與標籤數量
        _, num = struct.unpack(">II", f.read(8))
        labels = np.frombuffer(f.read(), dtype=np.uint8)
    return labels[:num]

# ========= 2. Utils ==========
def shuffle_numpy(X, y):
    """隨機打亂資料與標籤"""
    indices = np.arange(X.shape[0])
    np.random.shuffle(indices)
    return X[indices], y[indices]

def split_train_val(X, y, val_ratio=0.2):
    """依據比例分割訓練與驗證資料"""
    num_samples = X.shape[0]
    num_val = int(num_samples * val_ratio)
    X_train = X[num_val:]
    y_train = y[num_val:]
    X_val = X[:num_val]
    y_val = y[:num_val]
    return X_train, y_train, X_val, y_val

def one_hot(y, num_classes):
    """將整數標籤轉換成 one-hot 編碼"""
    one_hot_labels = np.zeros((y.shape[0], num_classes))
    one_hot_labels[np.arange(y.shape[0]), y] = 1
    return one_hot_labels

def accuracy(Y_pred, Y_true):
    """計算預測準確率（假設 Y_true 為 one-hot 編碼）"""
    pred_labels = np.argmax(Y_pred, axis=1)
    true_labels = np.argmax(Y_true, axis=1)
    return np.mean(pred_labels == true_labels)

# ========= 3. Model ==========
class MLP:
    def __init__(self, input_dim, hidden_dim, output_dim, weight_decay=0.0):
        self.W1 = np.random.randn(input_dim, hidden_dim) * 0.01
        self.b1 = np.zeros((1, hidden_dim))
        self.W2 = np.random.randn(hidden_dim, output_dim) * 0.01
        self.b2 = np.zeros((1, output_dim))
        self.lambda_ = weight_decay

    def relu(self, x):
        return np.maximum(0, x)

    def relu_deriv(self, x):
        return (x > 0).astype(float)

    def softmax(self, x):
        exps = np.exp(x - np.max(x, axis=1, keepdims=True))
        return exps / np.sum(exps, axis=1, keepdims=True)

    def forward(self, X):
        self.z1 = X @ self.W1 + self.b1
        self.a1 = self.relu(self.z1)
        self.z2 = self.a1 @ self.W2 + self.b2
        self.a2 = self.softmax(self.z2)
        return self.a2

    def compute_loss(self, Y_pred, Y_true):
        m = Y_true.shape[0]
        # 防止 log(0) 的問題，先 clip 預測值
        eps = 1e-8
        Y_pred_clipped = np.clip(Y_pred, eps, 1 - eps)
        data_loss = -np.sum(Y_true * np.log(Y_pred_clipped)) / m
        # 加入正則化項：0.5 * lambda * (||W1||^2 + ||W2||^2)
        reg_loss = 0.5 * self.lambda_ * (np.sum(self.W1 ** 2) + np.sum(self.W2 ** 2))
        return data_loss + reg_loss

    def backward(self, X, Y_true, Y_pred, lr=0.1):
        m = Y_true.shape[0]
        dz2 = (Y_pred - Y_true) / m
        dW2 = self.a1.T @ dz2 + self.lambda_ * self.W2
        db2 = np.sum(dz2, axis=0, keepdims=True)
        da1 = dz2 @ self.W2.T
        dz1 = da1 * self.relu_deriv(self.z1)
        dW1 = X.T @ dz1 + self.lambda_ * self.W1
        db1 = np.sum(dz1, axis=0, keepdims=True)
        # 更新參數
        self.W2 -= lr * dW2
        self.b2 -= lr * db2
        self.W1 -= lr * dW1
        self.b1 -= lr * db1

# ========= 4. Train Function ==========
def train(model, X_train, y_train, X_val, y_val, lr=0.1, epochs=100, use_early_stopping=False, patience=5):
    train_losses, val_losses, train_accs, val_accs = [], [], [], []
    best_val_loss = np.inf
    patience_count = 0

    for epoch in range(epochs):
        # 前向傳播計算訓練資料預測值與損失
        Y_pred_train = model.forward(X_train)
        loss = model.compute_loss(Y_pred_train, y_train)
        acc_train = accuracy(Y_pred_train, y_train)
        train_losses.append(loss)
        train_accs.append(acc_train)

        # 反向傳播並更新參數
        model.backward(X_train, y_train, Y_pred_train, lr)

        # 驗證資料的預測與損失計算
        Y_pred_val = model.forward(X_val)
        val_loss = model.compute_loss(Y_pred_val, y_val)
        acc_val = accuracy(Y_pred_val, y_val)
        val_losses.append(val_loss)
        val_accs.append(acc_val)

        print(f"Epoch {epoch:02d} | Train Loss: {loss:.4f} | Val Loss: {val_loss:.4f} | Train Acc: {acc_train:.4f} | Val Acc: {acc_val:.4f}")

        # 若啟用提前停止，根據驗證損失進行檢查
        if use_early_stopping:
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                patience_count = 0  # 驗證損失有改善，重置 patience_count
            else:
                patience_count += 1
            if patience_count >= patience:
                print(f"Early stopping triggered at epoch {epoch+1}")
                break

    return train_losses, val_losses, train_accs, val_accs

# ========= 5. Plotting ==========
def plot_curves(train_losses, val_losses, train_accs, val_accs, title):
    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.plot(train_losses, label="Train Loss")
    plt.plot(val_losses, label="Val Loss")
    plt.title("Loss Curve - " + title)
    plt.xlabel("Epochs")
    plt.ylabel("Loss")
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(train_accs, label="Train Acc")
    plt.plot(val_accs, label="Val Acc")
    plt.title("Accuracy Curve - " + title)
    plt.xlabel("Epochs")
    plt.ylabel("Accuracy")
    plt.legend()

    plt.tight_layout()
    plt.show()

# ========= 6. Main ==========
if __name__ == "__main__":
    # 載入資料集，請確認檔案名稱與路徑正確
    X = load_images("train-images (1).idx3-ubyte_____")
    y = load_labels("train-labels (1).idx1-ubyte_____")
    X, y = shuffle_numpy(X, y)
    X_train, y_train, X_val, y_val = split_train_val(X, y)
    y_train_oh = one_hot(y_train, 10)
    y_val_oh = one_hot(y_val, 10)

    input_dim = X_train.shape[1]
    hidden_dim = 128  # 可依需求調整隱藏層大小
    output_dim = 10

    # === OPTION 1: Early Stopping ===
    print("Training with Early Stopping:")
    model_early = MLP(input_dim, hidden_dim, output_dim, weight_decay=0.0)
    t1, v1, a1, a2 = train(model_early, X_train, y_train_oh, X_val, y_val_oh,
                           lr=0.1, epochs=100, use_early_stopping=True, patience=5)
    plot_curves(t1, v1, a1, a2, title="Early Stopping")

    # === OPTION 2: Weight Decay (L2 Regularization) ===
    print("Training with Weight Decay (L2 Regularization) for different λ values:")
    lambda_values = [0.0, 0.001, 0.01]  # 可嘗試的不同正則化強度
    for lam in lambda_values:
        print(f"\nTraining with weight_decay = {lam}")
        model_wd = MLP(input_dim, hidden_dim, output_dim, weight_decay=lam)
        t_loss, v_loss, t_acc, v_acc = train(model_wd, X_train, y_train_oh, X_val, y_val_oh,
                                             lr=0.1, epochs=100, use_early_stopping=False)
        plot_curves(t_loss, v_loss, t_acc, v_acc, title=f"Weight Decay (λ = {lam})")