# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jd1MZGU4mHhJQuGfYopLdgx_bYyIyk1S
"""

import os, zipfile, random, warnings, numpy as np, xml.etree.ElementTree as ET
import pandas as pd
from PIL import Image
from tqdm import tqdm
import matplotlib.pyplot as plt; import matplotlib.patches as patches

import torch
from torch.utils.data import DataLoader, Dataset
from torchvision.transforms import functional as F
from torchvision.models.detection import fasterrcnn_resnet50_fpn, FasterRCNN_ResNet50_FPN_Weights
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torch.cuda.amp import GradScaler, autocast
import albumentations as A
from albumentations.pytorch import ToTensorV2

warnings.filterwarnings("ignore", category=UserWarning)

# ─── CONFIG ─────────────────────────────────────────────────────
DEVICE         = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
NUM_CLASSES    = 10
BATCH_SIZE     = 2
EPOCHS         = 10
LR             = 1e-4
CONF_THRESHOLD = 0.7          # 推論分數閾值
SEED           = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)

# ─── 路徑 ───────────────────────────────────────────────────────
ZIP_FILE  = "./535306-machine-learning-final-project.zip"
DATA_DIR  = "./project_data"
if not os.path.exists(DATA_DIR):
    with zipfile.ZipFile(ZIP_FILE, 'r') as z: z.extractall(DATA_DIR)
print(f"[✓] dataset extracted → {DATA_DIR}")

TRAIN_IMG_DIR = os.path.join(DATA_DIR, "Dataset/train_images")
TRAIN_XML_DIR = os.path.join(DATA_DIR, "Dataset/train_annotations")
TEST_IMG_DIR  = os.path.join(DATA_DIR, "Dataset/test")
SAVE_CSV      = "./submission.csv"
SAVE_IMG_DIR  = "./output"; os.makedirs(SAVE_IMG_DIR, exist_ok=True)

LABEL_MAP = {'crazing':0,'inclusion':1,'patches':2,'pitted_surface':3,'rolled-in_scale':4,'scratches':5}
REV_LABEL = {v:k for k,v in LABEL_MAP.items()}

# ─── Albumentations pipeline ───────────────────────────────────
train_tf = A.Compose([
    A.HorizontalFlip(p=0.5),
    #A.RandomBrightnessContrast(p=0.5),
    A.CLAHE(p=0.2),
    A.RandomGamma(p=0.2),
    A.ShiftScaleRotate(shift_limit=0.05, scale_limit=0.1, rotate_limit=8, p=0.3),
    A.Resize(640, 640),
    A.ISONoise(p=0.2),             # 模擬攝影雜訊
    A.MotionBlur(p=0.2),           # 模糊增加泛化
    #A.RandomFog(fog_coef_lower=0.1, fog_coef_upper=0.3, p=0.1),
    ToTensorV2()
], bbox_params=A.BboxParams(format='pascal_voc',
                            label_fields=['class_labels'],
                            min_visibility=0.3))

plain_tf = A.Compose([A.Resize(640, 640), ToTensorV2()],
                     bbox_params=A.BboxParams(format='pascal_voc',
                                              label_fields=['class_labels']))

# ─── Dataset ───────────────────────────────────────────────────
class NEUDET(Dataset):
    def __init__(self, names, img_dir, xml_dir, tf=None):
        self.names, self.img_dir, self.xml_dir, self.tf = names, img_dir, xml_dir, tf
    def __len__(self): return len(self.names)

    def __getitem__(self, idx):
        fn  = self.names[idx]
        img = np.array(Image.open(os.path.join(self.img_dir, fn)).convert('RGB'))
        xml = os.path.join(self.xml_dir, fn.replace('.jpg', '.xml'))

        boxes, labels = [], []
        for obj in ET.parse(xml).getroot().findall('object'):
            labels.append(LABEL_MAP[obj.find('name').text])
            b = obj.find('bndbox'); boxes.append([float(b.find(t).text) for t in ('xmin','ymin','xmax','ymax')])
        boxes  = np.asarray(boxes ,dtype=np.float32)
        labels = np.asarray(labels,dtype=np.int64)

        if self.tf:
            aug   = self.tf(image=img, bboxes=boxes, class_labels=labels)
            img   = aug['image']                       # tensor uint8
            boxes = torch.tensor(aug['bboxes'])
            labels= torch.tensor(aug['class_labels'])
        else:
            img   = F.to_tensor(img)

        if img.dtype != torch.float32:
            img = img.to(torch.float32).div_(255.)

        target = {'boxes': boxes,
                  'labels': labels,
                  'image_id': torch.tensor([idx])}
        return img, target

def collate_fn(batch): return tuple(zip(*batch))

# ─── DataLoader ────────────────────────────────────────────────
all_imgs  = sorted([f for f in os.listdir(TRAIN_IMG_DIR) if f.endswith('.jpg')])
train_set = NEUDET(all_imgs, TRAIN_IMG_DIR, TRAIN_XML_DIR, train_tf)
train_ld  = DataLoader(train_set, BATCH_SIZE, shuffle=True, collate_fn=collate_fn)

# ─── Model ─────────────────────────────────────────────────────
weights = FasterRCNN_ResNet50_FPN_Weights.DEFAULT
model   = fasterrcnn_resnet50_fpn(weights=weights, box_score_thresh=CONF_THRESHOLD)
in_feat = model.roi_heads.box_predictor.cls_score.in_features
model.roi_heads.box_predictor = FastRCNNPredictor(in_feat, NUM_CLASSES)

for n,p in model.backbone.body.named_parameters():
    if any(l in n for l in ['layer1']):  # 冻 layer1~3
        p.requires_grad = False
model.to(DEVICE)

# ─── Optimizer / Scheduler ────────────────────────────────────
opt    = torch.optim.AdamW([p for p in model.parameters() if p.requires_grad], lr=LR, weight_decay=1e-4)
warm   = torch.optim.lr_scheduler.LinearLR(opt, start_factor=0.1, total_iters=3)
cosine = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=EPOCHS-3)

# ─── AMP Train ────────────────────────────────────────────────
scaler = GradScaler()
for ep in range(EPOCHS):
    model.train(); running=0.0
    for imgs, tgts in tqdm(train_ld, desc=f"Epoch {ep+1}/{EPOCHS}"):
        imgs = [i.to(DEVICE) for i in imgs]
        tgts = [{k:v.to(DEVICE) for k,v in t.items()} for t in tgts]

        opt.zero_grad()
        with autocast():
            loss_d = model(imgs, tgts)
            loss   = sum(loss_d.values())

        scaler.scale(loss).backward()
        from torch.nn.utils import clip_grad_norm_
        clip_grad_norm_(model.parameters(), max_norm=1.0)
        scaler.step(opt)
        scaler.update()
        running += loss.item()

    (warm if ep<3 else cosine).step()
    print(f"Epoch {ep+1}: loss {running/len(train_ld):.4f}")

# ─── Test & CSV / Plot ────────────────────────────────────────
model.eval(); rows=[]
with torch.no_grad():
    for fn in tqdm(sorted([f for f in os.listdir(TEST_IMG_DIR) if f.endswith('.jpg')]), desc='Test'):
        img_np = np.array(Image.open(os.path.join(TEST_IMG_DIR, fn)).convert('RGB'))
        with autocast():
            pred = model([F.to_tensor(img_np).to(DEVICE)])[0]

        keep = pred['scores'] >= CONF_THRESHOLD
        boxes, scores, labels = (pred['boxes'][keep].cpu(),
                                 pred['scores'][keep].cpu(),
                                 pred['labels'][keep].cpu())

        # --------  畫圖 ----------
        fig, ax = plt.subplots(1); ax.imshow(img_np)
        for bb, sc, lb in zip(boxes, scores, labels):
            x1,y1,x2,y2 = map(int, bb.tolist())
            ax.add_patch(patches.Rectangle((x1, y1), x2-x1, y2-y1,
                                           linewidth=2, edgecolor='red', facecolor='none'))  # ← 修正
            ax.text(x1, y1-5, f"{REV_LABEL[lb.item()]} {sc:.2f}",
                    color='red', fontsize=8)
        fig.savefig(os.path.join(SAVE_IMG_DIR, fn), dpi=150, bbox_inches='tight')
        plt.close(fig)
        # -------------------------

        if len(boxes):
            rows.append({
                'ID'  : fn,
                'label': REV_LABEL[labels[0].item()],
                'cf'  : ' '.join(f'{s:.2f}' for s in scores),
                'xmin': ' '.join(str(int(b[0])) for b in boxes),
                'ymin': ' '.join(str(int(b[1])) for b in boxes),
                'xmax': ' '.join(str(int(b[2])) for b in boxes),
                'ymax': ' '.join(str(int(b[3])) for b in boxes)
            })
        else:
            rows.append({'ID':fn,'label':'none','cf':'0','xmin':'0','ymin':'0',
                         'xmax':'0','ymax':'0'})

pd.DataFrame(rows).to_csv(SAVE_CSV, index=False)
print(f"\n✅ submission.csv → {SAVE_CSV}")
print(f"✅ annotated images → {SAVE_IMG_DIR}/")