# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UuOaQuFlJeMdcIggRvZYTQJfT6at8bJE
"""



import numpy as np
import matplotlib.pyplot as plt

# Load dataset
x_train, x_test, y_train, y_test = np.load('regression_data.npy', allow_pickle=True)

# Reshape targets
y_train = y_train.reshape(-1,)
y_test = y_test.reshape(-1,)

# Add bias term (column of ones)
train_data = np.hstack((x_train, np.ones((x_train.shape[0], 1))))
test_data = np.hstack((x_test, np.ones((x_test.shape[0], 1))))

# ==============================
# Task 1: Standard Linear Regression (Gradient Descent)
# ==============================
def linear_regression_train(x_train, y_train, lr=1e-3, iterations=7000):
    weight = np.random.randn(x_train.shape[1])
    loss = np.zeros(iterations)

    for i in range(iterations):
        y_pred = x_train @ weight  # Compute predicted values

        loss[i] = np.mean((y_train - y_pred) ** 2)  # Compute MSE

        # Compute gradients
        gradient = (-2 / x_train.shape[0]) * (x_train.T @ (y_train - y_pred))  # Compute gradient

        # Update weights
        weight -= lr * gradient  # Apply gradient descent update

    return weight, loss

weight_standard, loss_standard = linear_regression_train(train_data, y_train)

print("\n=== Standard Linear Regression Parameters ===")
print(f'Weight (m): {weight_standard[0]}')  # Print weight[0]
print(f'Bias (b): {weight_standard[1]}')  # Print weight[1]

# ==============================
# Task 2: Compute MSE
# ==============================
def compute_mse(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)  # Compute MSE formula

y_pred_standard = test_data @ weight_standard  # Compute predictions for test data
mse_standard = compute_mse(y_test, y_pred_standard)

print("\n=== Mean Squared Error (Standard Regression) ===")
print(f'MSE: {mse_standard}')

# ==============================
# Task 3: Ridge Regression (Gradient Descent)
# ==============================
def ridge_regression_train(x_train, y_train, lr=1e-3, iterations=7000, lambda_reg=0.1):
    weight = np.random.randn(x_train.shape[1])
    loss = np.zeros(iterations)

    for i in range(iterations):
        y_pred = x_train @ weight  # Compute predicted values

        loss[i] = np.mean((y_train - y_pred) ** 2) + lambda_reg * np.sum(weight ** 2)  # Compute MSE with L2 regularization

        # Compute gradients with regularization
        gradient = (-2 / x_train.shape[0]) * (x_train.T @ (y_train - y_pred)) + 2 * lambda_reg * weight  # Compute weight gradient with L2 regularization

        # Update weights
        weight -= lr * gradient  # Apply gradient descent update

    return weight, loss

weight_ridge, loss_ridge = ridge_regression_train(train_data, y_train)

print("\n=== Ridge Regression Parameters ===")
print(f'Weight (m): {weight_ridge[0]}')
print(f'Bias (b): {weight_ridge[1]}')

y_pred_ridge = test_data @ weight_ridge  # Compute predictions for test data
mse_ridge = compute_mse(y_test, y_pred_ridge)

print("\n=== Mean Squared Error (Ridge Regression) ===")
print(f'MSE: {mse_ridge}')

# ==============================
# Task 4: Plot Loss Curve
# ==============================
plt.figure(figsize=(8, 6))
plt.plot(loss_standard, label="Standard Regression Loss")
plt.plot(loss_ridge, label="Ridge Regression Loss", linestyle="dashed")
plt.xlabel("Iterations")
plt.ylabel("Loss (MSE)")
plt.legend()
plt.title("Loss Curve Comparison")
plt.show()

# ==============================
# Task 5: Closed-form Ridge Regression
# ==============================
def closed_form_ridge(x_train, y_train, lambda_reg=0.1):
    I = np.eye(x_train.shape[1])
    return np.linalg.inv(x_train.T @ x_train + lambda_reg * I) @ x_train.T @ y_train  # Compute closed-form solution (Equation 4.27)

weight_closed_form = closed_form_ridge(train_data, y_train)
y_pred_closed_form = test_data @ weight_closed_form  # Compute predictions for test data
mse_closed_form = compute_mse(y_test, y_pred_closed_form)

print("\n=== Closed-form Ridge Regression Parameters ===")
print(f'Weight (m): {weight_closed_form[0]}')
print(f'Bias (b): {weight_closed_form[1]}')
print("\n=== Mean Squared Error (Closed-form Ridge Regression) ===")
print(f'MSE: {mse_closed_form}')

# ==============================
# Task 6: Predictive Distribution
# ==============================
predictive_mean = y_pred_closed_form  # Predictive mean is simply the predicted values
predictive_variance = np.var(y_test - y_pred_closed_form)  # Compute variance of residuals

print("\n=== Predictive Distribution ===")
print(f'Predictive Mean (first 5 values): {predictive_mean[:5]}')
print(f'Predictive Variance: {predictive_variance}')

# ==============================
# Task 7: Plot Predictions
# ==============================
plt.figure(figsize=(8, 6))
plt.scatter(x_test[:, 0], y_test, label="True Values", color='blue')
plt.scatter(x_test[:, 0], y_pred_standard, label="Standard Regression Predictions", color='red', alpha=0.6)
plt.scatter(x_test[:, 0], y_pred_ridge, label="Ridge Regression Predictions", color='green', alpha=0.6)
plt.scatter(x_test[:, 0], y_pred_closed_form, label="Closed-form Ridge Predictions", color='purple', alpha=0.6)
plt.xlabel("Feature")
plt.ylabel("Target")
plt.legend()
plt.title("Predictions vs True Values")
plt.show()

# ==============================
# Plot Confidence Intervals
# ==============================
plt.figure(figsize=(8, 6))
plt.scatter(x_test[:, 0], y_test, label="True Values", color='blue')
plt.scatter(x_test[:, 0], y_pred_closed_form, label="Predictions", color='red', alpha=0.6)
plt.fill_between(x_test[:, 0], y_pred_closed_form - predictive_variance, y_pred_closed_form + predictive_variance,
                 color='gray', alpha=0.2, label="Confidence Interval")
plt.xlabel("Feature")
plt.ylabel("Target")
plt.legend()
plt.title("Predictive Confidence Interval")
plt.show()