# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hkB2_5V18UgKjfu1rLU-MGtCK8Fx-NFo
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import struct
import os

print(os.listdir())

# ----------------------------
# Step 1: 載入 MNIST 資料集
# ----------------------------
def load_mnist_images(filename):
    with open(filename, 'rb') as f:
        _magic, num, rows, cols = struct.unpack(">IIII", f.read(16))
        images = np.frombuffer(f.read(), dtype=np.uint8).reshape(num, rows * cols)
        return images / 255.0

def load_mnist_labels(filename):
    with open(filename, 'rb') as f:
        _magic, num = struct.unpack(">II", f.read(8))
        labels = np.frombuffer(f.read(), dtype=np.uint8)
        return labels

# ⚠️ 請根據你的實際檔案名稱修改這裡！
X_train = load_mnist_images("train-images.idx3-ubyte___")[:500]
y_train = load_mnist_labels("train-labels.idx1-ubyte___")[:500]
X_test = load_mnist_images("t10k-images.idx3-ubyte___")[:200]
y_test = load_mnist_labels("t10k-labels.idx1-ubyte___")[:200]

# ----------------------------
# Step 2: 激活函數
# ----------------------------
def relu(x):  # Eq. 6.17
    return np.maximum(0, x)

def tanh(x):  # Eq. 6.14
    return np.tanh(x)

def softplus(x):  # Eq. 6.16
    return np.log1p(np.exp(x))

def leaky_relu(x, alpha=0.1):  # Eq. 6.18
    return np.maximum(0, x) + alpha * np.minimum(0, x)

def one_hot(y, num_classes=10):
    oh = np.zeros((len(y), num_classes))
    for i, val in enumerate(y):
        oh[i, val] = 1.0
    return oh

def cross_entropy(y_pred, y_true):
    """
    y_pred: (N, K) softmax outputs
    y_true: (N, K) one-hot labels
    """
    eps = 1e-12  # 防止 log(0)
    return -np.sum(y_true * np.log(y_pred + eps)) / y_pred.shape[0]

def softmax(a):
    """
    a: (N, K) raw scores
    return: (N, K) softmax probabilities
    """
    a_stable = a - np.max(a, axis=1, keepdims=True)
    exp_a = np.exp(a_stable)
    return exp_a / np.sum(exp_a, axis=1, keepdims=True)

def forward_pass(X, weights, activations):

    out = X
    for W, act in zip(weights, activations):
        z = out @ W
        out = act(z)
    return out

# ----------------------------
# Step 3: 隨機初始化網路
# ----------------------------
np.random.seed(42)
input_size = 784
hidden1 = 128
hidden2 = 64
#hidden3 = 64
output_size = 10
epochs = 30
best_loss = float('inf')
best_weights = None

W1 = np.random.uniform(-0.1, 0.1, size=(input_size, hidden1))
W2 = np.random.uniform(-0.1, 0.1, size=(hidden1, hidden2))
W3 = np.random.uniform(-0.1, 0.1, size=(hidden2, output_size))
#W4 = np.random.uniform(-0.1, 0.1, size=(hidden3, output_size))
weights = [W1, W2, W3]

activations = [leaky_relu, leaky_relu, softmax]

y_test_oh = one_hot(y_test, 10)  # One-hot once即可

for epoch in range(epochs):
 # forward pass (用同一組 weights)
    y_pred_proba = forward_pass(X_test, weights, activations)
    # 計算 loss
    loss = cross_entropy(y_pred_proba, y_test_oh)

    # 如果比之前好，就記錄
    if loss < best_loss:
        best_loss = loss
        best_weights = [w.copy() for w in weights]


# ----------------------------
# Step 4: 推論
# ----------------------------
y_test_pred_proba = forward_pass(X_test, weights, activations)
y_test_pred = np.argmax(y_test_pred_proba, axis=1)

# ----------------------------
# Step 5: 評估與顯示
# ----------------------------
def compute_confusion_matrix(y_true, y_pred, num_classes=10):
    cm = np.zeros((num_classes, num_classes), dtype=int)
    for t, p in zip(y_true, y_pred):
        cm[t, p] += 1
    return cm

def compute_metrics_verbose(cm):
    num_classes = cm.shape[0]
    total = np.sum(cm)
    total_correct = 0

    for i in range(num_classes):
        tp = cm[i, i]
        fp = np.sum(cm[:, i]) - tp
        fn = np.sum(cm[i, :]) - tp
        tn = total - (tp + fp + fn)

        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0

        total_correct += tp

        print(f"Class {i}:")
        print(f"TP: {tp}, FP: {fp}, FN: {fn}, TN: {tn}")
        print(f"Precision: {precision:.4f}")
        print(f"Recall: {recall:.4f}")
        print(f"F1 Score: {f1:.4f}\n")

    overall_accuracy = total_correct / total
    print(f"Overall Accuracy: {overall_accuracy:.4f}")

def plot_confusion_matrix(cm):
    plt.figure(figsize=(6,5))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.title("Confusion Matrix")
    plt.show()

def compute_roc_for_class(y_true_binary, y_score):
    thresholds = np.linspace(0,1,50)
    tpr_vals = []
    fpr_vals = []
    P = np.sum(y_true_binary==1)
    N = np.sum(y_true_binary==0)

    for thr in thresholds:
        y_pred_positive = (y_score >= thr).astype(int)
        tp = np.sum((y_pred_positive==1) & (y_true_binary==1))
        fp = np.sum((y_pred_positive==1) & (y_true_binary==0))
        tpr = tp / P if P>0 else 0
        fpr = fp / N if N>0 else 0
        tpr_vals.append(tpr)
        fpr_vals.append(fpr)
    return np.array(fpr_vals), np.array(tpr_vals)

def plot_roc(y_true_oh, y_pred_proba):
    plt.figure(figsize=(7,6))
    num_classes = y_true_oh.shape[1]
    for c in range(num_classes):
        fpr, tpr = compute_roc_for_class(y_true_oh[:, c], y_pred_proba[:, c])
        plt.plot(fpr, tpr, label=f"Class {c}")
    plt.plot([0,1],[0,1], '--', color='gray')
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("ROC Curve (One-vs-Rest)")
    plt.legend()
    plt.show()

# ----------------------------
# Step 7: 執行結果
# ----------------------------
cm = compute_confusion_matrix(y_test, y_test_pred)

print("=== Classification Report (Detailed) ===")
compute_metrics_verbose(cm)

plot_confusion_matrix(cm)

y_test_oh = one_hot(y_test, 10)
plot_roc(y_test_oh, y_test_pred_proba)